config/routes.rb
Rails.application.routes.draw do

  root 'pages#login'
  match '/home',to:'pages#home',via:'get'
  match '/callback',to:'pages#callback',via:'get'
  match '/done',to:'pages#done',via:'get'
  match '/succ',to:'pages#succ',via:'get'
  resources :pots
  resources :levels do
    member do
      get 'check'
    end
  end
  resources :stores do
    resources :orders do
    end
  end

end

app/models/level.rb
class Level < ActiveRecord::Base
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :store
end

app/models/pot.rb
class Pot < ActiveRecord::Base
end

app/models/store.rb
class Store < ActiveRecord::Base
  has_many :order
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
end

app/controllers/levels_controller.rb
class LevelsController < ApplicationController
  def show
    @level=Level.find(params[:id])
  end
  def check
    @level=Level.find(params[:id])
    getans=params[:op]
    if getans == @level.op
      render 'right'
    else
      render 'wrong'
    end
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def new
    @order=Order.new
  end
  def done
  end
  def create
    @order=Order.new(order_params)
    if @order.save
      redirect_to "/done"
    end
  end

  private
    def order_params
      params.permit(:phone,:people)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @username=params[:username]
  end
  def done
  end
  def succ
  end
  def callback
    res=Net::HTTP.get(URI("https://openapi.baidu.com/oauth/2.0/token?grant_type=authorization_code&code="+params[:code]+"&client_id=GLGRNxPvGgQxGvkH1bz9u7mx&client_secret=FWcvSgwQodO2kF6r2plUGYlfophK9ueT&redirect_uri=http%3A%2F%2Fvps.wengchichi.com%2Fcallback"))
    body=JSON.parse(res)
    print "========"
    res=Net::HTTP.get(URI("https://openapi.baidu.com/rest/2.0/passport/users/getInfo?access_token="+body['access_token']+"&format=json"))
    print res=JSON.parse(res)
    print res['username']
    redirect_to "/home?username="+res['username']
  end
end

app/controllers/pots_controller.rb
class PotsController < ApplicationController
  def index
    @pots=Pot.all
  end
  def show
    @pot= Pot.find(params[:id])
  end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  def index
    @stores=Store.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/levels_helper.rb
module LevelsHelper
end

app/helpers/order_helper.rb
module OrderHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pots_helper.rb
module PotsHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>Ratchet template page</title>
<meta name="viewport" content="initial-scale=1, maximum-scale=1, user-scalable=no, minimal-ui">
<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-status-bar-style" content="black">
<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
<%= csrf_meta_tags %>
<script type="text/javascript" name="baidu-tc-cerfication" src="http://apps.bdimg.com/cloudaapi/lightapp.js#e6ece07e51f0b91f11603fdf60871847"></script><script type="text/javascript">window.bd && bd._qdc && bd._qdc.init({app_id: 'f0b9a01c2ac8ace3c4729cdd'});</script>
</head>
<body>
<%= yield %>
</body>
</html>

app/views/levels/right.html.erb
<header class="bar bar-nav header-bar">
  <h1 class="title"><%= t('right') %></h1>
</header>
<div class="content">
  <center>
    <%= image_tag(File.join('biglevel',@level.pic),height: '250', width: '300') %>
  </center>
  <h3><%= @level.answer %></h3>
  <% if @level.id != 3 %>
    <a href="/levels/<%= @level.id + 1 %>" > <button class="btn btn-negative btn-block"> <%= t('go_next') %> </button> </a>
  <% else %>
    <a href="/succ" > <button class="btn btn-negative btn-block"> <%= t('go_succ') %> </button> </a>
  <% end %>
</div>

app/views/levels/show.html.erb
<header class="bar bar-nav header-bar">
  <a class="icon icon-left-nav pull-left" href="/home"></a>
  <h1 class="title">Level <%= @level.id %></h1>
</header>
<div class="content">
  <button class="btn btn-block"><%= @level.question %></button>
  <a href="/levels/<%= @level.id %>/check?op=1" > <button class="btn btn-primary btn-block"> <%= @level.a %> </button> </a>
  <a href="/levels/<%= @level.id %>/check?op=2" > <button class="btn btn-positive btn-block"> <%= @level.b %> </button> </a>
  <a href="/levels/<%= @level.id %>/check?op=3" > <button class="btn btn-negative btn-block"> <%= @level.c %> </button> </a>
</div>

app/views/levels/wrong.html.erb
<header class="bar bar-nav header-bar">
  <h1 class="title"><%= t('wrong') %></h1>
</header>
<div class="content">
  <center>
    <%= image_tag(File.join('biglevel',@level.pic),height: '250', width: '300') %>
  </center>
  <h3><%= @level.answer %></h3>
  <a href="/home" > <button class="btn btn-negative btn-block"> <%= t('go_home') %> </button> </a>
</div>

app/views/orders/new.html.erb
<header class="bar bar-nav header-bar">
  <a class="icon icon-left-nav pull-left" href="/stores"></a>
  <h1 class="title"><%= t('order_info') %></h1>
</header>
<div class="content">
  <div class="board">
    <form method="post" action="<%= store_orders_path %>">
        <input type="text" name="phone" placeholder="<%= t('phone') %>">
        <input type="text" name="people" placeholder="<%= t('people') %>">
        <button class="btn btn-positive btn-block"><%= t('confirm_submit') %></button>
    </form>
  </div>
</div>

app/views/pages/done.html.erb
<header class="bar bar-nav header-bar">
  <a class="icon icon-left-nav pull-left" href="/stores"></a>
  <h1 class="title"><%= t('operation_done') %></h1>
</header>
<div class="content">
  <div class="slide">
    <center>
      <%= image_tag("done.jpg", height: '450', width: '300') %>
    </center>
  </div>
</div>

app/views/pages/home.html.erb
<header class="bar bar-nav header-bar">
  <h1 class="title"><%= @username %><%= t('haidilao') %></h1>
</header>
<div class="content">
  <div class="slide">
    <center>
      <%= image_tag("logo.jpg", height: '200', width: '300') %>
    </center>
  </div>
  <div class="card">
    <ul class="table-view">
      <li class="table-view-cell">
      <a class="push-right" href="/stores">
        <strong><%= t('order') %></strong>
      </a>
      </li>
      <li class="table-view-cell">
        <a class="push-right" href="/pots">
          <strong><%= t('pot') %></strong>
        </a>
      </li>
      <li class="table-view-cell">
        <a class="push-right" href="/levels/1">
          <strong><%= t('go_level') %></strong>
        </a>
      </li>
    </ul>
  </div>
</div>

app/views/pages/login.html.erb
<header class="bar bar-nav header-bar">
  <h1 class="title"><%= t('haidilao') %></h1>
</header>
<div class="content">
  <center>
  <%= image_tag('login.jpg',height: '250', width: '300') %>
  </center>
  <a href="http://openapi.baidu.com/oauth/2.0/authorize?response_type=code&client_id=GLGRNxPvGgQxGvkH1bz9u7mx&redirect_uri=http%3A%2F%2Fvps.wengchichi.com%2Fcallback&scope=super_msg&state=eadfe44b7a3021b0f9dd456e7ed76998&display=page"> 
  <button class="btn btn-negative btn-block"> <%= t('baidu') %> </button> </a>
</div>

app/views/pages/succ.html.erb
<header class="bar bar-nav header-bar">
  <a class="icon icon-left-nav pull-left" href="/home"></a>
  <h1 class="title"><%= t('succ') %></h1>
</header>
<div class="content">
  <div class="slide">
    <center>
      <%= image_tag("succ.jpg", height: '450', width: '300') %>
    </center>
  </div>
</div>

app/views/pots/index.html.erb
<header class="bar bar-nav header-bar">
  <a class="icon icon-left-nav pull-left" href="/home"></a>
  <h1 class="title"><%= t('pot') %></h1>
</header>
<div class="content">
  <ul class="table-view">

    <% @pots.each do |pot| %>
      <li class="table-view-cell media">
      <a class="navigate-right" href="/pots/<%= pot.id %>">
          <%= image_tag(File.join('smallpot',pot.pic),height: '42', width: '42',class:'media-object pull-left') %>
          <div class="media-body">
            <%= pot.name %>
            <p> <%= pot.suit %> </p>
          </div>
        </a>
      </li>
    <% end %>

  </ul>
</div>

app/views/pots/show.html.erb
<header class="bar bar-nav header-bar">
  <a class="icon icon-left-nav pull-left" href="/home"></a>
  <h1 class="title"><%= @pot.name %></h1>
</header>
<div class="content">
  <center>
    <%= image_tag(File.join('bigpot',@pot.pic),height: '250', width: '300') %>
  </center>
  <h3><%= @pot.feature %></h3>
</div>

app/views/stores/index.html.erb
<header class="bar bar-nav header-bar">
  <a class="icon icon-left-nav pull-left" href="/home"></a>
  <h1 class="title"><%= t('nearby_store') %></h1>
</header>
<div class="content">
  <ul class="table-view">

    <% @stores.each do |store| %>
      <li class="table-view-cell media">
      <a class="navigate-right" href="/stores/<%= store.id %>/orders/new">
          <%= image_tag(File.join('smallpic',store.smallpic),height: '42', width: '42',class:'media-object pull-left') %>
          <div class="media-body">
            <%= store.name %>
            <p> <%= store.address %> </p>
          </div>
        </a>
      </li>
    <% end %>

  </ul>
</div>